
const NEW_GAME = 'NEW_GAME'

const UPDATE_HOVERED_TILE_COORDINATES = 'UPDATE_HOVERED_TILE_COORDINATES'

const NEXT_TURN = 'NEXT_TURN'

const MAP_DRAG = 'MAP_DRAG'

const ZOOM_MAP_IN = 'ZOOM_IN'

const ZOOM_MAP_OUT = 'ZOOM_MAP_OUT'

const INITIATE_GIVE_FIEF_MODE = 'INITIATE_GIVE_FIEF_MODE'

const GIVE_FIEF_TO_NOBLE = 'GIVE_FIEF_TO_NOBLE'

const UNINITIATE_GIVE_FIEF_MODE = 'UNINITIATE_GIVE_FIEF_MODE'

const RAISE_ARMY = 'RAISE_ARMY'

const SELECT = 'SELECT'

const UPDATE_ARMY_DESTINATION = 'UPDATE_ARMY_DESTINATION'

const DISBAND_ARMY = 'DISBAND_ARMY'

const ADJUST_MAP_OFFSET = 'ADJUST_MAP_OFFSET'

const TOGGLE_ARMY_MODE = 'TOGGLE_ARMY_MODE'

export default { 
  NEW_GAME,
  UPDATE_HOVERED_TILE_COORDINATES,
  NEXT_TURN, 
  MAP_DRAG, 
  ZOOM_MAP_IN, 
  ZOOM_MAP_OUT, 
  INITIATE_GIVE_FIEF_MODE, 
  GIVE_FIEF_TO_NOBLE,
  UNINITIATE_GIVE_FIEF_MODE,
  RAISE_ARMY,
  SELECT,
  UPDATE_ARMY_DESTINATION,
  DISBAND_ARMY,
  ADJUST_MAP_OFFSET,
  TOGGLE_ARMY_MODE
}